# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Board name
CONFIG_ZMK_KEYBOARD_NAME="Corne Keyboard"
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# WPM shown as a graph only
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=n
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n

# Side screens: no animation (custom image goes here next)
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=n
